### ISSUE TITLE
ratio wrong when terminal very wide

### ISSUE THREAD

**Issue by alexmyczko** [autopawn/3d-ascii-viewer-c#5]
so i've tried to make the terminal very large on a 16:9 screen, and the knight gets really fat:
`./viewer -h $LINES -w $(echo $COLUMNS-1|bc) /usr/share/games/brutalchess/models/knight.obj

is there a way to not stretch the object? well probably not. it's 3d, but fonts are usually double high than wide (+/-), depending on the font, and screen/resolution (pixels being square or not, visible with circles)

**Comment by autopawn** [comment]
Hello, now it is assumed that the terminal characters have a `height/ratio` of 1.8. This allows to automatically scale the model instead of stretching it.

A different `height/ratio` can be provided with the `-a` parameter, or the model can be stretched again with the `-s` parameter.

Does this solve the issue?

**Comment by alexmyczko** [comment]
Indeed, thank you!
