### ISSUE TITLE
interactive mode distance

### ISSUE THREAD

**Issue by alexmyczko** [autopawn/3d-ascii-viewer-c#8]
would it be possible to implement zoom in/out with +/- in interactive mode?

**Comment by autopawn** [comment]
Yes, but I think it requires some discussion, here are my thoughts:

One of the possible uses I see for the interactive mode is finding the angle to use for the `--snap` mode, so adding that feature to it may require also adding it to the `--snap` mode somehow. For this, it is probably better to include the zoom level as a new option than as part of the `--snap` option (breaking backwards compatibility if 3 parameters are expected instead of 2), which can also be applied to the default "animation" mode.

Since the size of the model is normalized for presentation (the scale is the maximum that allows the model to fit completely in the screen in any possible rotation), the units somewhat lose meaning, so it would probably have to be in %, where 100 is the default. I think we can call this option `-z`.

Regarding the use cases, I think this may be useful for people making animations using many times the --snap command, but I would like to avoid entering the feature creep of adding more camera control options like the offset.

**Comment by autopawn** [comment]
Added `-z` option and support for zoom in the `--interactive` mode.

**Comment by alexmyczko** [comment]
is there a trick to fix the 3d model inside the viewer (like the banana for scale is upside down)? http://sid.ethz.ch/debian/3d-ascii-viewer-c/banan.obj

**Comment by autopawn** [comment]
> is there a trick to fix the 3d model inside the viewer (like the banana for scale is upside down)? http://sid.ethz.ch/debian/3d-ascii-viewer-c/banan.obj

I think in this case the user would have to import the model in an edition program, such as blender, and properly export is as OBJ with the default options. 

Maybe I could add options for inverting each one of the 3 axis, but it would require some thinking.
